"""Local modeling package for weather experiments."""

from .config import DEFAULT_MODEL_CONFIG_PATH
from .data import (
    ArcoEra5CompatibilityReport,
    ArcoEra5FuXiDataConfig,
    ArcoEra5FuXiDataset,
    DEFAULT_ARCO_ERA5_URL,
    build_arco_era5_dataloader,
    inspect_arco_era5_dataset,
)
from .models import (
    DEFAULT_MODEL_PATH,
    FuXiEncoderOutput,
    FuXiIntrinsic,
    FuXiIntrinsicConfig,
    FuXiLowerRes,
    FuXiLowerResConfig,
    FuXiLowerResDecoder,
    FuXiLowerResEncoder,
    FuXiShort,
    FuXiShortConfig,
    build_exact_fuxi_short_graph,
    build_fuxi_time_embeddings,
    inspect_exact_fuxi_short_graph,
    summarize_short_onnx_architecture,
)
from .training import (
    IntrinsicTrainingConfig,
    MainTrainingConfig,
    run_intrinsic_model_smoke_test,
    run_main_model_smoke_test,
    train_intrinsic_model,
    train_main_model,
)

__all__ = [
    "DEFAULT_MODEL_CONFIG_PATH",
    "DEFAULT_ARCO_ERA5_URL",
    "DEFAULT_MODEL_PATH",
    "ArcoEra5CompatibilityReport",
    "ArcoEra5FuXiDataConfig",
    "ArcoEra5FuXiDataset",
    "FuXiEncoderOutput",
    "FuXiIntrinsic",
    "FuXiIntrinsicConfig",
    "FuXiLowerRes",
    "FuXiLowerResConfig",
    "FuXiLowerResDecoder",
    "FuXiLowerResEncoder",
    "FuXiShort",
    "FuXiShortConfig",
    "build_exact_fuxi_short_graph",
    "build_arco_era5_dataloader",
    "build_fuxi_time_embeddings",
    "inspect_arco_era5_dataset",
    "inspect_exact_fuxi_short_graph",
    "summarize_short_onnx_architecture",
    "IntrinsicTrainingConfig",
    "MainTrainingConfig",
    "run_intrinsic_model_smoke_test",
    "run_main_model_smoke_test",
    "train_intrinsic_model",
    "train_main_model",
]
